### ISSUE TITLE
Add link to Suraj Gupta's explanation of R lookup?

### ISSUE THREAD

**Issue by vspinu** [hadley/r-pkgs#204]
I have just stumbled on the most user friendly description of [R lookup mechanism](http://obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/). Given that the namespace chapter glosses over this issue it might be good idea to link to that page.

**Comment by hadley** [comment]
I think this is great material, we should adapt (i.e. redraw with citation) the most important stuff. There's some overlap with adv-r, but NAMESPACEs also need a good description here

**Comment by jennybc** [comment]
FWIW the new location of this post is https://blog.thatbuthow.com/how-r-searches-and-finds-stuff/

**Comment by jennybc** [comment]
I am coming to the conclusion that the [Special Environments section of Advanced R](https://adv-r.hadley.nz/environments.html#special-environments) is a better resource for us to draw on, at this point in history. The (very useful!) blog post was written in March 2012, only a few months after package namespaces became a true requirement in R 2.14.0 Great Pumpkin, released 2011-10-31. The R world has made a lot of progress re: how to use and think about package namespaces since 2012 and Advanced R is a better representation of that.

**Comment by hadley** [comment]
Sounds reasonable to me!
