### ISSUE TITLE
Built-in functions modify in place

### ISSUE THREAD

**Issue by mohamed-180** [hadley/r-pkgs#506]
when i wrote this in rstudio i get :
x <- 1:10
address(x)
#> [1] "0x103945110"

x[2] <- 7L
address(x)
#> [1] "0x107ec9178"

the book says the address won't be change , any explain .
regards .

**Comment by jennybc** [comment]
This seems like content more related to [Advanced R](https://adv-r.hadley.nz). Do you perhaps mean to file an issue there?

**Comment by jennybc** [comment]
OK I'm going to close this here since it does not pertain to this book about writing R packages.

If you think there is an error in Advanced R, you can open a more specific issue in its repo, referencing the exact section you're talking about.

Alternatively, this might actually be a better question to ask on <https://community.rstudio.com>.
