### ISSUE TITLE
Code block typo

### ISSUE THREAD

**Issue by jimr1603** [hadley/r-pkgs#597]
https://r-pkgs.org/vignettes.html#knitr

\`\`\`{r}

should be 

 \`\`\`{r}

**Comment by hadley** [comment]
That's what prevents knitr processing as a regular knitr block. But you shouldn't see that symbol. What browser and operating system are you using?

**Comment by jimr1603** [comment]
Google Chrome 75.0.3770.100 (Official Build) (32-bit)
Revision cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@
{#1033}
OS Windows 10 OS Version 1709 (Build 16299.1365)

**Comment by jimhester** [comment]
The vertical tab does show up as whitespace for me as well, at least on chrome, I opened a PR to convert these characters to zero width spaces, which should not show up as whitespace on all browsers I think.

I tried a few other non-printing ASCII characters and they all seemed to show up as whitespace, which is why I went the unicode route.
