### ISSUE TITLE
Using the tidyverse in packages

### ISSUE THREAD

**Issue by hadley** [hadley/r-pkgs#609]
Following script in: https://github.com/hadley/tidy-tools/blob/master/script/4-tidyverse.Rmd

**Comment by jennybc** [comment]
I do now reference this in the new "package within" example, i.e. "don't Import tidyverse, do this instead ...".

Do you still want more?

Reading the lesson linked above ... I'm ambivalent. To a certain extent, a lot of that feels fairly specific to dplyr or tidy eval. Does such guidance really belong in a general "R Packages" book? However, I can get on board with it, because obviously dplyr / tidyverse / tidy eval are a very major presence.

**Comment by hadley** [comment]
I think that's adequate. I think maybe it could also get a more general paragraph where we talk about dependencies. i.e. something like before you require a heavy package, check to make sure you can't use require some component of that package (with the tidyverse and maybe devtools as examples)

**Comment by jennybc** [comment]
Do we think this belongs in the metadata chapter (basically DESCRIPTION) or in the NAMESPACE chapter? Or somewhere else entirely?

The metadata/DESCRIPTION chapter has gained quite a bit of content re: "how to think about dependencies", because that's where we talk about Depends/Imports/Suggests.

I feel like we need to better clarify where different content goes. This may be a helpful distinction for us:

* How to decide whether to depend on another package at all and, if you do, in which way (e.g. Imports vs. Suggests)
* Once you depend on another package, mechanics around its use inside your package.

**Comment by hadley** [comment]
Seems like it should go in the DESCRIPTION package for now, maybe pending a chapter that just talks about dependencies?

**Comment by jennybc** [comment]
It is starting to feel like a new chapter on dependencies might be useful.
