### ISSUE TITLE
"Edit this page" link broken 

### ISSUE THREAD

**Issue by rerickson-usgs** [hadley/r-pkgs#626]
Hi,

I am trying to help update the book as I read it. (you still reference `devtools::` rather than `usethis::`).

BUT, the `Edit this page` link is broken on http://r-pkgs.had.co.nz/tests.html (it is
https://github.com/hadley/r-pkgs/edit/master/tests.rmd) and I'm unsure where I should edit to fix this.

**Comment by jennybc** [comment]
The 1st edition is published at: http://r-pkgs.had.co.nz
Yes (almost?) all "edit this page" buttons are broken, because capitalization of file names has changed in the underlying source repo.

This may be just as well, because the 1st edition is "frozen" and the text you see there is increasingly *different* from the in-progress 2nd edition. They are growing increasingly divergent.

Edit links on the in-process 2nd edition work fine:
https://r-pkgs.org

The 1st edition vs 2nd edition is explained on the https://r-pkgs.org landing page and in the README here.

So I think the only aspect of this that could *maybe* be improved is already covered by:
Old website should contain note that never version is available #632

**Comment by rerickson-usgs** [comment]
@jennybc Thank you for explaining this. I hadn't realized the 2nd edition was on a different webpage.
