### ISSUE TITLE
Chapter 15: all cpp functions go in 1 file?

### ISSUE THREAD

**Issue by beevabeeva** [hadley/r-pkgs#687]
It is not clear from the book whether all cpp functions should reside in the file `code.cpp` in `src`. 
I did try making a separate file `my_func.cpp`, and after calling `load_all()`,  there is no corresponding code for `my_func` in `RcppExports.cpp`. So it indicates that it is the case that everything should go in `code.cpp`.

Maybe not the right place to ask, but why **is** this the way? Why isn't having multiple cpp files preferred? We do after all have multiple files for R functions in `R/`...

I have only been using R for a month and have had to deal with some very obscure things. Glad this book exists. Thank you 

P.S 
Apologies in advance if it is indeed explicit in the book and I just missed it.

**Comment by jennybc** [comment]
This chapter is going to get heavily revised for. the 2nd edition, since cpp11 has arrived on the scene since this chapter was first written. It is also possible that such content will be significantly trimmed back in this book, in favour of other venues where it can get the full treatment it deserves. Here are some better places to look than R Packages at the moment:

https://adv-r.hadley.nz/rcpp.html

https://cpp11.r-lib.org

For all of these reasons, I'm going to close this issue.

**Comment by beevabeeva** [comment]
Thanks @jennybc
