### ISSUE TITLE
Kable and multibyte string (Package-within.Rmd)

### ISSUE THREAD

**Issue by GerardTromp** [hadley/r-pkgs#690]
Greetings!

In case some other people run into this problem.

I tried to reproduce the timestamp code in Package-within-Rmd (lines 596 to 631). [In case the line numbers change, this is 
the section where timestamps are converted to a common reference time.]

My system and Rstudio are set to UTF-8, but the timestamp column was Latin-1, but the encoding is not set. This caused the error
`nchar: invalid multibyte string`
when executing the `knitr::kable` instruction.

After much initial floundering it seems that the solution is to set the encoding. 
I settled for the base R 
`Encoding(colleagues[["timestamp"]])<-"latin1"`

There has to be a tidyverse format for this, but at this point I was just happy to be able to solve the encoding problem.

**Comment by jennybc** [comment]
Setting the encoding to `"latin1"` like this cannot be a good idea *unconditionally*, i.e. to include in the book. If you are on Windows (which I suppose is true if you got timestamps in latin1) and have set your "system and Rstudio ... to UTF-8", you are already in a tricky situation. Luckily by the time R Packages get published R 4.2 will be out, which will hopefully improve encoding matters for R users on Windows.

In any case, thanks for drawing my attention to this section, because I now see I'm using some locales that apparently I can't assume to be present in the GHA environment. And now I will take explicit steps to generate any locales that I use.

**Comment by jennybc** [comment]
Being specific about UTF-8 in all the relevant locales seems to have resolved this.
