### ISSUE TITLE
Imports in DESCRIPTION does not load package

### ISSUE THREAD

**Issue by jedwards24** [hadley/r-pkgs#706]
I think [Section 13.2](https://r-pkgs.org/namespace.html#search-path) is incorrect in the following part:
>Listing a package in either Depends or Imports ensures that it’s installed when needed. The main difference is that where Imports just loads the package, Depends attaches it.

Listing a package in the `Imports` field in DESCRIPTION will not load the package. It is loaded if used in `import` or `importFrom` in the NAMESPACE, or when `::` is used. An example: glue is listed in `Imports` for stringr but it is not loaded on `library(stringr)`.

```
> library(stringr)
> ?glue
No documentation for ‘glue’ in specified packages and libraries:
you could try ‘??glue’
```

Thank you for the 2nd edition. It has been very helpful.

**Comment by hadley** [comment]
That's the technical difference between loading and attaching.

**Comment by jennybc** [comment]
> ... Imports just load the package ...

I suppose the potential for misunderstanding is created by the fact that this loading of a package listed in Imports does not necessarily happen at the moment the main package is attached. The timing depends on how the dependency is used inside the main package and how the main package is being used.

Let's continue the concrete example of stringr and glue. (reprex is no good for such detailed studies of loaded namespaces, because the use of knitr adds all sorts of stuff to the loaded namespaces.)

Baseline, in a plain vanilla R session:

``` r
> loadedNamespaces()
[1] "compiler"  "graphics"  "utils"     "grDevices" "stats"     "datasets" 
[7] "methods"   "base"
```

Attach stringr. Newly loaded namespaces are stringr (for obvious reasons) and a subset of the packages listed in stringr's Imports (magrittr, stringi). 

``` r
> library(stringr)
> loadedNamespaces()
 [1] "compiler"  "magrittr"  "graphics"  "tools"     "utils"     "grDevices"
 [7] "stats"     "datasets"  "stringi"   "methods"   "stringr"   "base"
```

Use `str_c()`. No change in loaded namespaces.

``` r   
> str_c("hello, ", "world!")
[1] "hello, world!"
> loadedNamespaces()
 [1] "compiler"  "magrittr"  "graphics"  "tools"     "utils"     "grDevices"
 [7] "stats"     "datasets"  "stringi"   "methods"   "stringr"   "base"
```

Use `str_glue()`. Now glue is also among the loaded namespaces (as is crayon, via glue).

``` r
> str_glue("the alphabet begins with {LETTERS[1]}")
the alphabet begins with A
> loadedNamespaces()
 [1] "compiler"  "magrittr"  "graphics"  "tools"     "glue"      "utils"    
 [7] "grDevices" "crayon"    "stats"     "datasets"  "stringi"   "methods"  
[13] "stringr"   "base"    
```

I'm not convinced that this merits rewording. I'm not sure there's anything to be gained for a typical package and maintainer to try and identify exactly when something in Imports will be loaded. The main goal of this section is to hammer home the differences between Imports and Depends.

**Comment by hadley** [comment]
Yeah, I think this is a detail that we don't need to get into in this book.

**Comment by jennybc** [comment]
Just to create connections/links, here is another concrete study of when things get loaded: https://github.com/hadley/r-pkgs/issues/828#issuecomment-1221193352
