### ISSUE TITLE
Ch 6.6 “no visible binding” note

### ISSUE THREAD

**Issue by shannonpileggi** [hadley/r-pkgs#857]
Our book club really enjoyed Ch 6! It was great to see the process of transforming an R script to a robust package.

At the end of 6.6, there is discussion of the "no visible binding note" with two solutions presented.

```
# option 1 (then you should also put utils in Imports)
utils::globalVariables("english", "temp"))

# option 2
english <- temp <- NULL
```

I believe this is the only mention of this note and a solution in the book, and I wanted to confirm that this is what you want readers to take away as a recommended solution. 

If so, consider (1) caveating these solutions as viable for few variables, and (2) more prominently referencing the _Programming with dplyr vignette_ in the body of the text as a reference for other approaches (rather than as a footnote).

I'm happy to make a PR if you agree with the suggestions.

**Comment by jennybc** [comment]
No, I suspect this will probably come up again in the yet-to-revised chapter on `R CMD check`. So I'm labelling this issue with that.

**Comment by hadley** [comment]
Having recently stared at a bunch of packages that use `.data` extensively, I'm not sure that I'd now recommend it over `globalVariables`/assigning a dummy variable.

**Comment by ddsjoberg** [comment]
@shannonpileggi and I are in the same bookclub :)

I am a tidyverse-first learner of R, and as a result my early packages contain many references to `.data`.  FWIW, I encourage colleagues to use the `.data` and `.env` prefixes because (in addition to silencing the global variables note) removes any ambiguity about whether you're referring to a column in a data frame vs an external vector, e.g. `filter(.data$column %in% .env$column)`.
