### ISSUE TITLE
Ch15 Advanced testing techniques: define memoisation

### ISSUE THREAD

**Issue by shannonpileggi** [hadley/r-pkgs#884]
It would be helpful to define memoise/memoisation.

**Comment by jennybc** [comment]
I want to push back on this a bit. Sort of specifically, but more because it's a concrete example of a phenomenon that undoubtedly happens elsewhere in the book: using a term that isn't universally familiar.

I think this is the sole occurrence of "memoise" in the book, i.e. it's not something we really address at all. There is a hidden comment right around there, stating that I'd like to find a suitable wild-caught example, but so far have not. I think I'd define the term more if there was more coverage of it.

But I think I'm basically comfortable with people Googling it. It might be the writing fatigue talking, but I don't think it's possible to make the book completely self-contained. And that's OK.

What do you think?

**Comment by shannonpileggi** [comment]
I agree that for terms that are self-evidently searchable, like "memoise", then it is ok to leave out the defintion and curious readers could seek supplemental information elsewhere.

On the other hand, for the guarding phrasing in issue #866, that one seems a bit trickier. Because "guard" is a familiar word, readers might not be triggered to do a google search of it, or if they do, might not end up with an intended interpretation.

**Comment by jennybc** [comment]
Yeah I agree that #866 is a more compelling case for elaboration and am glad you think it's acceptable to let things be re: "memoise". Closing this but leaving the other open.
