### ISSUE TITLE
Chapter 3: System Setup - RStudio IDE Preview version is not yet on Posit website

### ISSUE THREAD

**Issue by ateucher** [hadley/r-pkgs#934]
It's recommended that people use the preview version of RStudio, but it is not yet on the new Posit website. See here: https://community.rstudio.com/t/how-to-find-rstudio-preview-in-the-new-posit-co-site/155376. I'm not sure if it will be available when the book goes to publication so it might be necessary to remove that recommendation?

**Comment by jennybc** [comment]
I suspect this (the preview version website issue) will get sorted out, so I think we just need to find a way to word this that conveys people will benefit from staying relatively current with the IDE, up to and including running a preview version. The preview version has become less important than in the past, because the release cadence has gotten more often and more regular.
