### ISSUE TITLE
Chapter 5 - Fundamental Workflows review

### ISSUE THREAD

**Issue by ateucher** [hadley/r-pkgs#939]
“How to Get an RStudio Project”: This paragraph introduces the concept of a usethis project - I think this could be confusing, especially in light of the discussion of “Projects” and “projects” just prior. It is well-described a bit later, perhaps wecould provide a forward reference to [5.3.5](https://r-pkgs.org/workflow101.html#rstudio-project-vs.-active-usethis-project)?

Regarding keyboard shortcuts and command palette (#802, #697). I agree these could be highlighted and summarized... perhaps keyboard shortcuts in a table or appendix at the end of the chapter? Maybe the command palette could get a callout box?

**Comment by jennybc** [comment]
Yes, I agree a forward reference to the usethis project section would be a good addition.

I don't think we should make a table to keyboard shortcuts, because it's destined to become out-of-date. I think we should offer general encouragement to use keyboard shortcuts (we certainly highlight many specific shortcuts throughout the book) and tell people how to get the IDE to help them see/configure shortcuts.

A callout for the command palette sounds like a good idea. This is one is tricky for me to write, since I don't use it personally, but I know lots of people find it really makes me them more productive.

**Comment by ateucher** [comment]
Great! I do like the command palette, so I'll try to write something, and I'll add a reference to the usethis project section. I think that makes sense about the shelf-life of keyboard shortcuts.
