### ISSUE TITLE
Consider mentioning vscode?

### ISSUE THREAD

**Issue by ateucher** [hadley/r-pkgs#949]
Visual Studio Code wasn't really on the landscape when the first edition of the book was released, but it's now obviously a major player. I feel like VSCode should be mentioned [alongside Emacs + ESS & Vim here](https://github.com/hadley/r-pkgs/blob/d5c9b45a9e1f896c684061516e863b78a03a16d5/introduction.Rmd#L61) (and/or consider whether or not Emacs and Vim are still in wide enough use with the target audience of the book - I don't have a good feel for that)?

**Comment by jennybc** [comment]
Yeah we should definitely include VS Code and in a way that reflects it's a more popular thing for folks to adopt now than the emacs/vim option. I don't think we should remove emacs/vim entirely, but perhaps they could move to a footnote. At this point, I think an _existing_ power user of emacs or vim might want to work with R that way. But I seriously doubt many newcomers to R / package development would choose to learn emacs/vim in order to use them as an IDE for R.

So yes a PR would be great.
